version: "3.8"

services:
  app:
    build: .
    container_name: inss_app
    volumes:
      - .:/app
    environment:
      host: db
      username: postgres
      password: postgres
      database: inss_dev
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inss_dev
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
