default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("host") || "db" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("username") %>
  password: <%= ENV.fetch("password") %>


development:
  <<: *default
  database: <%= ENV.fetch("database", "inss_challenge_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("database_test", "inss_challenge_test") %>

production:
  primary: &primary_production
    <<: *default
    database: inss_challenge_production
    username: inss_challenge
    password: <%= ENV["INSS_CHALLENGE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: inss_challenge_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: inss_challenge_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: inss_challenge_production_cable
    migrations_paths: db/cable_migrate
